/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package city.nursing.home;


import Database.DBNewAccount;
import Manager.NewAccount;
import javax.swing.JOptionPane;
public class CreateNewAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateNewAccount
     */
    public CreateNewAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelEmployeeId = new javax.swing.JLabel();
        jTextFieldEmployeeId = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxTypesOfAccount = new javax.swing.JComboBox<>();
        jButtonRegisterNewAccount = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonBackToHome = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 26)); // NOI18N
        jLabel1.setText("Create a New Account");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account-login_17515464.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEmployeeId.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelEmployeeId.setText("Employee ID :");
        jPanel2.add(jLabelEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 31, -1, -1));

        jTextFieldEmployeeId.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldEmployeeId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldEmployeeId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextFieldEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 32, 181, -1));

        jLabelUsername.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelUsername.setText("Username :");
        jPanel2.add(jLabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 87, -1, -1));

        jTextFieldUsername.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 88, 181, -1));

        jLabelPassword.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelPassword.setText("Password :");
        jPanel2.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 133, 131, -1));

        jTextFieldPassword.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 134, 181, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("Select Account Type :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 179, -1, -1));

        jComboBoxTypesOfAccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBoxTypesOfAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cashier", "Doctor", "Administrator" }));
        jComboBoxTypesOfAccount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxTypesOfAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypesOfAccountActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxTypesOfAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 212, -1, -1));

        jButtonRegisterNewAccount.setBackground(new java.awt.Color(255, 255, 153));
        jButtonRegisterNewAccount.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButtonRegisterNewAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-user_8802155.png"))); // NOI18N
        jButtonRegisterNewAccount.setText("Register New Account");
        jButtonRegisterNewAccount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRegisterNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterNewAccountActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRegisterNewAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 275, 266, 44));

        jTextArea1.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 337, 340, 103));

        jButtonBackToHome.setBackground(new java.awt.Color(255, 255, 102));
        jButtonBackToHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBackToHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross_14875490.png"))); // NOI18N
        jButtonBackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToHomeActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBackToHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/151932061_10553586 (1).jpg"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterNewAccountActionPerformed
        NewAccount newAccount = new NewAccount();
        
        String employeeId = jTextFieldEmployeeId.getText();
        String userName = jTextFieldUsername.getText();
        String password = jTextFieldPassword.getText();
        String typesOfAccount = jComboBoxTypesOfAccount.getSelectedItem().toString();
        
        if(employeeId.isEmpty() || userName.isEmpty() || password.isEmpty() || typesOfAccount.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in all fields.","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
      
      newAccount.setEmployeeID(jTextFieldEmployeeId.getText().toString());
      newAccount.setUsername(jTextFieldUsername.getText().toString());
      newAccount.setPassword(jTextFieldPassword.getText().toString());
      newAccount.setTypesOfAccount(jComboBoxTypesOfAccount.getSelectedItem().toString());
      
              String newAccountDetails = "EmployeeID : " + newAccount.getEmployeeID() + "\n" +
                               "UserName : " + newAccount.getUsername() + "\n" +
                               "Password : " + newAccount.getPassword() + "\n" +
                               "Types Of Account : " + newAccount.getTypesOfAccount() + "\n";

 
        jTextArea1.append(newAccountDetails);
        System.out.println(newAccountDetails);
      
      DBNewAccount saveAccount = new DBNewAccount();
      saveAccount.SaveAccountDetails(newAccount,"newAccount.txt");
      JOptionPane.showMessageDialog(this, "Account Successfully Registered", "Success",JOptionPane.INFORMATION_MESSAGE);
      
      
      
    }//GEN-LAST:event_jButtonRegisterNewAccountActionPerformed

    private void jComboBoxTypesOfAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypesOfAccountActionPerformed
        
    }//GEN-LAST:event_jComboBoxTypesOfAccountActionPerformed

    private void jButtonBackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToHomeActionPerformed
        this.dispose();
        
        
    }//GEN-LAST:event_jButtonBackToHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateNewAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackToHome;
    private javax.swing.JButton jButtonRegisterNewAccount;
    private javax.swing.JComboBox<String> jComboBoxTypesOfAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelEmployeeId;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldEmployeeId;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
