/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package city.nursing.home;

import Database.ReadNewpatient;
import Database.newPatient;
import city.nursing.home.homecityNursing;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
public class PatientBookingInformation extends javax.swing.JFrame {

    /**
     * Creates new form PatientBookingInformation
     */
    public PatientBookingInformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jButtonBackToMain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 28)); // NOI18N
        jLabel1.setText("All Patient Booking Details");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/106335427_10058467 (1).jpg"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man_6629075.png"))); // NOI18N
        jLabel3.setText("Add new Patient");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("New Patient");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye-exam_15756017.png"))); // NOI18N
        jLabel4.setText("View Patient Details");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Patient Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(255, 255, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_4124311 (1).png"))); // NOI18N

        jTextFieldSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jButtonSearch.setBackground(new java.awt.Color(255, 255, 102));
        jButtonSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSearch)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSearch)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButtonBackToMain.setBackground(new java.awt.Color(255, 255, 102));
        jButtonBackToMain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBackToMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left-chevron_10117897.png"))); // NOI18N
        jButtonBackToMain.setText("Back To Main");
        jButtonBackToMain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBackToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonBackToMain, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jButton1))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBackToMain, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     this.setVisible(false);
    AddNewPatient addNewPatientFrame = new AddNewPatient();
    addNewPatientFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        newPatient readnewPatient = new newPatient();
        ReadNewpatient newPatient = new ReadNewpatient();
        String content = newPatient.readNewPatient("newPatient.txt");
        jTextArea1.setText(content);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonBackToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToMainActionPerformed
        this.setVisible(false);
        homecityNursing backToMain = new homecityNursing();
        backToMain.setVisible(true);
    }//GEN-LAST:event_jButtonBackToMainActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
    String searchName = jTextFieldSearch.getText().trim();
    
     String searchTerm = jTextFieldSearch.getText().trim(); 

    
    if (searchTerm.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter a Doctor ID or Name to search.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String filePath = "newDoctors.txt"; 
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[]{"Doctor ID", "Doctor Name", "Date of Birth", "Years of Experience", "Specialization", "Available Days"});

    boolean found = false; 

    try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
        String line;
        String savedDoctorId = "", savedDoctorName = "", savedDateOfBirth = "", savedYearsOfExperience = "", savedSpecialization = "", savedAvailableDays = "";


        while ((line = reader.readLine()) != null) {
         
            if (line.startsWith("Doctor ID: ")) {
                savedDoctorId = line.substring("Doctor ID: ".length()).trim();
            } else if (line.startsWith("Name: Dr.")) {
                savedDoctorName = line.substring("Name:".length()).trim();
            } else if (line.startsWith("Date of Birth: ")) {
                savedDateOfBirth = line.substring("Date of Birth: ".length()).trim();
            } else if (line.startsWith("Years of Experience: ")) {
                savedYearsOfExperience = line.substring("Years of Experience: ".length()).trim();
            } else if (line.startsWith("Specialization: ")) {
                savedSpecialization = line.substring("Specialization: ".length()).trim();
            } else if (line.startsWith("Available Days: ")) {
                savedAvailableDays = line.substring("Available Days: ".length()).trim();
            }

          
            if (!savedDoctorId.isEmpty() && !savedDoctorName.isEmpty() && !savedDateOfBirth.isEmpty() &&
                !savedYearsOfExperience.isEmpty() && !savedSpecialization.isEmpty() && !savedAvailableDays.isEmpty()) {

              
                if (savedDoctorId.contains(searchTerm) || savedDoctorName.equalsIgnoreCase(searchTerm)) {
                    found = true;
                    model.addRow(new Object[]{savedDoctorId, savedDoctorName, savedDateOfBirth, savedYearsOfExperience, savedSpecialization, savedAvailableDays});
                }

              
                savedDoctorId = "";
                savedDoctorName = "";
                savedDateOfBirth = "";
                savedYearsOfExperience = "";
                savedSpecialization = "";
                savedAvailableDays = "";
            }
        }

      
        if (found) {
            JTable resultTable = new JTable(model);
            JScrollPane scrollPane = new JScrollPane(resultTable);
            scrollPane.setPreferredSize(new java.awt.Dimension(800, 200)); 
            JOptionPane.showMessageDialog(this, scrollPane, "Search Results", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No doctor record found for the given search term: " + searchTerm, "Record Not Found", JOptionPane.WARNING_MESSAGE);
        }

    } catch (FileNotFoundException e) {
        JOptionPane.showMessageDialog(this, "File not found: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error reading the file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    
           
//    String filepath = "newPatient.txt";
//
//    try (BufferedReader reader = new BufferedReader(new FileReader(filepath))) {
//        String line;
//        String savedName = "";
//        String savedAge = "";
//        String savedContact = "";
//        String savedDOB = "";
//        String savedGender = "";
//        String savedCategory = "";
//        String savedNewPatientDate = "";
//
//        boolean found = false;
//
//       
//        while ((line = reader.readLine()) != null) {
//         
//            if (line.startsWith("Name: ")) {
//                savedName = line.substring("Name: ".length()).trim();
//            }
//         
//            else if (line.startsWith("Age: ")) {
//                savedAge = line.substring("Age: ".length()).trim();
//            }
//         
//            else if (line.startsWith("Contact: ")) {
//                savedContact = line.substring("Contact: ".length()).trim();
//            }
//           
//            else if (line.startsWith("Date of Birth: ")) {
//                savedDOB = line.substring("Date of Birth: ".length()).trim();
//            }
//           
//            else if (line.startsWith("Gender: ")) {
//                savedGender = line.substring("Gender: ".length()).trim();
//            }
//        
//            else if (line.startsWith("Category: ")) {
//                savedCategory = line.substring("Category: ".length()).trim();
//            }
//          
//            else if (line.startsWith("New Patient Date: ")) {
//                savedNewPatientDate = line.substring("New Patient Date: ".length()).trim();
//            }
//
//         
//            if (!savedName.isEmpty() && !savedAge.isEmpty() && !savedContact.isEmpty() &&
//                !savedDOB.isEmpty() && !savedGender.isEmpty() && !savedCategory.isEmpty() &&
//                !savedNewPatientDate.isEmpty()) {
//            
//                if (savedName.equalsIgnoreCase(searchName)) {
//                    found = true;
//             
//                    String record = "Name: " + savedName + "\n" +
//                                   "Age: " + savedAge + "\n" +
//                                   "Contact: " + savedContact + "\n" +
//                                   "Date of Birth: " + savedDOB + "\n" +
//                                   "Gender: " + savedGender + "\n" +
//                                   "Category: " + savedCategory + "\n" +
//                                   "New Patient Date: " + savedNewPatientDate;
//                    JOptionPane.showMessageDialog(this, record, "Patient Record Found", JOptionPane.INFORMATION_MESSAGE);
//                    jTextArea1.setText(record);
//                    break; 
//                }
//               
//                savedName = "";
//                savedAge = "";
//                savedContact = "";
//                savedDOB = "";
//                savedGender = "";
//                savedCategory = "";
//                savedNewPatientDate = "";
//            }
//        }
//
//        if (!found) {
////            JOptionPane.showMessageDialog(this, "No patient record found for the name: " + searchName, "Record Not Found", JOptionPane.WARNING_MESSAGE);
//        }
//    } catch (FileNotFoundException e) {
////        JOptionPane.showMessageDialog(this, "File not found: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//    } catch (IOException e) {
////        JOptionPane.showMessageDialog(this, "Error reading the file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//    } catch (Exception e) {
////        JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//    }
//    
//    
//    
//    String filePath = "newPatient.txt";
//
//    DefaultTableModel model = new DefaultTableModel();
//    model.setColumnIdentifiers(new String[]{"Name", "Age", "Contact", "DOB", "Gender", "Category", "New Patient Date"});
//
//    try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
//        String line;
//        String savedName = "", savedAge = "", savedContact = "", savedDOB = "", savedGender = "", savedCategory = "", savedNewPatientDate = "";
//        boolean found = false;
//
//        while ((line = reader.readLine()) != null) {
//            if (line.startsWith("Name: ")) {
//                savedName = line.substring("Name: ".length()).trim();
//            } else if (line.startsWith("Age: ")) {
//                savedAge = line.substring("Age: ".length()).trim();
//            } else if (line.startsWith("Contact: ")) {
//                savedContact = line.substring("Contact: ".length()).trim();
//            } else if (line.startsWith("Date of Birth: ")) {
//                savedDOB = line.substring("Date of Birth: ".length()).trim();
//            } else if (line.startsWith("Gender: ")) {
//                savedGender = line.substring("Gender: ".length()).trim();
//            } else if (line.startsWith("Category: ")) {
//                savedCategory = line.substring("Category: ".length()).trim();
//            } else if (line.startsWith("New Patient Date: ")) {
//                savedNewPatientDate = line.substring("New Patient Date: ".length()).trim();
//            }
//
//         
//            if (!savedName.isEmpty() && !savedAge.isEmpty() && !savedContact.isEmpty() &&
//                !savedDOB.isEmpty() && !savedGender.isEmpty() && !savedCategory.isEmpty() &&
//                !savedNewPatientDate.isEmpty()) {
//
//                if (savedName.equalsIgnoreCase(searchName)) {
//                    found = true;
//                    model.addRow(new Object[]{savedName, savedAge, savedContact, savedDOB, savedGender, savedCategory, savedNewPatientDate});
//                }
//
//                
//                savedName = "";
//                savedAge = "";
//                savedContact = "";
//                savedDOB = "";
//                savedGender = "";
//                savedCategory = "";
//                savedNewPatientDate = "";
//            }
//        }
//
//        if (found) {
//            JTable resultTable = new JTable(model);
//            JScrollPane scrollPane = new JScrollPane(resultTable);
//            scrollPane.setPreferredSize(new java.awt.Dimension(600, 200)); // Set table size
//            JOptionPane.showMessageDialog(this, scrollPane, "Search Results", JOptionPane.INFORMATION_MESSAGE);
//        } else {
//            JOptionPane.showMessageDialog(this, "No patient record found for the name: " + searchName, "Record Not Found", JOptionPane.WARNING_MESSAGE);
//        }
//    } catch (FileNotFoundException e) {
//        JOptionPane.showMessageDialog(this, "File not found: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//    } catch (IOException e) {
//        JOptionPane.showMessageDialog(this, "Error reading the file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//    }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientBookingInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientBookingInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientBookingInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientBookingInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientBookingInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBackToMain;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
